version: '3.4'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: comuniteca
    ports:
      - 5432:5432

  redis:
    container_name: redis
    image: 'redis'
    restart: always
    ports:
      - "6379:6379"